export type FasmetriCategorySlug =
  | "adult"
  | "audio"
  | "auto-accessories"
  | "beauty"
  | "books-stationery"
  | "cables-adapters"
  | "computer-accessories"
  | "computers"
  | "furniture"
  | "gaming"
  | "home-appliances"
  | "home-garden"
  | "kids"
  | "kitchen-dishes"
  | "laptops"
  | "mobiles"
  | "monitors"
  | "other"
  | "pets"
  | "phone-accessories"
  | "photo-video"
  | "refrigerators"
  | "small-appliances"
  | "sport"
  | "tablets"
  | "tablet-accessories"
  | "televisions"
  | "washing-machines"
  | "wearables";

export type CategoryRule = {
  slug: FasmetriCategorySlug;
  titleKeywords: readonly string[];
  titleKeywordGroups?: readonly (readonly string[])[];
  contextKeywords?: readonly string[];
  negativeKeywords?: readonly string[];
  shopKeywords?: readonly string[];
  titleWeight?: number;
  requiresTitleMatch?: boolean;
};

export const FALLBACK_CATEGORY: FasmetriCategorySlug = "other";

export const PUBLIC_CATEGORY_TAXONOMY: Record<
  FasmetriCategorySlug,
  { nameKa: string; nameEn: string; public: boolean }
> = {
  adult: { nameKa: "18+ პროდუქტები", nameEn: "Adult products", public: false },
  audio: { nameKa: "აუდიო", nameEn: "Audio", public: true },
  "auto-accessories": { nameKa: "ავტო აქსესუარები", nameEn: "Auto accessories", public: true },
  beauty: { nameKa: "სილამაზე და მოვლა", nameEn: "Beauty", public: true },
  "books-stationery": { nameKa: "წიგნები და საკანცელარიო", nameEn: "Books and stationery", public: true },
  "cables-adapters": { nameKa: "კაბელები და ადაპტერები", nameEn: "Cables and adapters", public: true },
  "computer-accessories": { nameKa: "კომპიუტერის აქსესუარები", nameEn: "Computer accessories", public: true },
  computers: { nameKa: "კომპიუტერები და ნაწილები", nameEn: "Computers and parts", public: true },
  furniture: { nameKa: "ავეჯი", nameEn: "Furniture", public: true },
  gaming: { nameKa: "Gaming", nameEn: "Gaming", public: true },
  "home-appliances": { nameKa: "საყოფაცხოვრებო ტექნიკა", nameEn: "Home appliances", public: true },
  "home-garden": { nameKa: "სახლი და ბაღი", nameEn: "Home and garden", public: true },
  kids: { nameKa: "საბავშვო", nameEn: "Kids", public: true },
  "kitchen-dishes": { nameKa: "სამზარეულო და ჭურჭელი", nameEn: "Kitchen and dishes", public: true },
  laptops: { nameKa: "ლეპტოპები", nameEn: "Laptops", public: true },
  mobiles: { nameKa: "მობილურები", nameEn: "Mobiles", public: true },
  monitors: { nameKa: "მონიტორები", nameEn: "Monitors", public: true },
  other: { nameKa: "სხვა", nameEn: "Other", public: true },
  pets: { nameKa: "ცხოველების მოვლა", nameEn: "Pet supplies", public: true },
  "phone-accessories": { nameKa: "ტელეფონის აქსესუარები", nameEn: "Phone accessories", public: true },
  "photo-video": { nameKa: "ფოტო/ვიდეო", nameEn: "Photo and video", public: true },
  refrigerators: { nameKa: "მაცივრები", nameEn: "Refrigerators", public: true },
  "small-appliances": { nameKa: "მცირე ტექნიკა", nameEn: "Small appliances", public: true },
  sport: { nameKa: "სპორტი", nameEn: "Sport", public: true },
  tablets: { nameKa: "ტაბლეტები", nameEn: "Tablets", public: true },
  "tablet-accessories": { nameKa: "ტაბლეტის აქსესუარები", nameEn: "Tablet accessories", public: true },
  televisions: { nameKa: "ტელევიზორები", nameEn: "Televisions", public: true },
  "washing-machines": { nameKa: "სარეცხი მანქანები", nameEn: "Washing machines", public: true },
  wearables: { nameKa: "სმარტ საათები", nameEn: "Wearables", public: true },
};

Object.assign(PUBLIC_CATEGORY_TAXONOMY, {
  adult: { nameKa: "18+ პროდუქტები", nameEn: "Adult products", public: false },
  audio: { nameKa: "აუდიო", nameEn: "Audio", public: true },
  "auto-accessories": { nameKa: "ავტო აქსესუარები", nameEn: "Auto accessories", public: true },
  beauty: { nameKa: "სილამაზე და მოვლა", nameEn: "Beauty", public: true },
  "books-stationery": { nameKa: "წიგნები და საკანცელარიო", nameEn: "Books and stationery", public: true },
  "cables-adapters": { nameKa: "კაბელები და ადაპტერები", nameEn: "Cables and adapters", public: true },
  "computer-accessories": { nameKa: "კომპიუტერის აქსესუარები", nameEn: "Computer accessories", public: true },
  computers: { nameKa: "კომპიუტერები და ნაწილები", nameEn: "Computers and parts", public: true },
  furniture: { nameKa: "ავეჯი", nameEn: "Furniture", public: true },
  gaming: { nameKa: "Gaming", nameEn: "Gaming", public: true },
  "home-appliances": { nameKa: "საყოფაცხოვრებო ტექნიკა", nameEn: "Home appliances", public: true },
  "home-garden": { nameKa: "სახლი და ბაღი", nameEn: "Home and garden", public: true },
  kids: { nameKa: "საბავშვო", nameEn: "Kids", public: true },
  "kitchen-dishes": { nameKa: "სამზარეულო და ჭურჭელი", nameEn: "Kitchen and dishes", public: true },
  laptops: { nameKa: "ლეპტოპები", nameEn: "Laptops", public: true },
  mobiles: { nameKa: "მობილურები", nameEn: "Mobiles", public: true },
  monitors: { nameKa: "მონიტორები", nameEn: "Monitors", public: true },
  other: { nameKa: "სხვა", nameEn: "Other", public: true },
  pets: { nameKa: "ცხოველების მოვლა", nameEn: "Pet supplies", public: true },
  "phone-accessories": { nameKa: "ტელეფონის აქსესუარები", nameEn: "Phone accessories", public: true },
  "photo-video": { nameKa: "ფოტო/ვიდეო", nameEn: "Photo and video", public: true },
  refrigerators: { nameKa: "მაცივრები", nameEn: "Refrigerators", public: true },
  "small-appliances": { nameKa: "მცირე ტექნიკა", nameEn: "Small appliances", public: true },
  sport: { nameKa: "სპორტი", nameEn: "Sport", public: true },
  tablets: { nameKa: "ტაბლეტები", nameEn: "Tablets", public: true },
  "tablet-accessories": { nameKa: "ტაბლეტის აქსესუარები", nameEn: "Tablet accessories", public: true },
  televisions: { nameKa: "ტელევიზორები", nameEn: "Televisions", public: true },
  "washing-machines": { nameKa: "სარეცხი მანქანები", nameEn: "Washing machines", public: true },
  wearables: { nameKa: "სმარტ საათები", nameEn: "Wearables", public: true },
} satisfies Record<FasmetriCategorySlug, { nameKa: string; nameEn: string; public: boolean }>);

export const KITCHEN_DISH_KEYWORDS = [
  "coffee cup",
  "coffee mug",
  "mug",
  "cup",
  "drinking glass",
  "water glass",
  "wine glass",
  "shot glass",
  "glass cup",
  "glass set",
  "glassware",
  "plate",
  "bowl",
  "cookware",
  "pan",
  "pot",
  "knife set",
  "fork",
  "spoon",
  "ყავის ჭიქა",
  "ჭიქა",
  "ფინჯანი",
  "თეფში",
  "ჯამი",
  "ქვაბი",
  "ტაფა",
  "დანა",
  "ჩანგალი",
  "კოვზი",
  "ჭიქების ნაკრები",
  "ზეთის დისპენსერი",
  "milk jug",
  "რძის დოქი",
] as const;

export const KITCHEN_DISH_NEGATIVE_KEYWORDS = [
  "screen protector",
  "tempered glass",
  "protective glass",
  "privacy glass",
  "full screen glass",
  "camera glass",
  "phone glass",
  "glass protector",
  "screen glass",
  "ეკრანის შუშა",
] as const;

export const FURNITURE_NEGATIVE_KEYWORDS = [
  ...KITCHEN_DISH_KEYWORDS,
  "glass",
  "coffee accessories",
  "kitchen tools",
  "soap dispenser",
  "vase",
  "candle",
  "car charger",
  "power station",
  "projector",
  "ssd",
  "charger",
  "cable",
  "monitor stand",
  "monitor",
  "display mount",
  "mounting arm",
  "laptop stand",
  "desk mount",
  "lamp",
  "home decor small",
  "საპნის დისპენსერი",
  "ლარნაკი",
  "სანთელი",
  "მანქანის დამტენი",
  "დამტენი",
  "კაბელი",
] as const;

export const CATEGORY_RULES: readonly CategoryRule[] = [
  {
    slug: "adult",
    titleKeywords: ["adult", "18+", "erotic", "sex toy", "dildo", "vibrator", "სექს", "ვიბრატორი", "დილდო"],
    contextKeywords: ["sex shop", "adult products"],
    titleWeight: 100,
  },
  {
    slug: "kitchen-dishes",
    titleKeywords: KITCHEN_DISH_KEYWORDS,
    negativeKeywords: KITCHEN_DISH_NEGATIVE_KEYWORDS,
    contextKeywords: ["tableware", "dishes", "kitchen utensil", "ჭურჭელი", "სამზარეულოს აქსესუარი"],
    shopKeywords: ["dishes", "tableware", "kitchenware", "ჭურჭელი"],
    titleWeight: 96,
  },
  {
    slug: "auto-accessories",
    titleKeywords: [
      "dash cam",
      "dashcam",
      "car charger",
      "car holder",
      "phone holder",
      "mobile holder",
      "magnetic mobile holder",
      "magnetic holder",
      "car magnetic",
      "compressor",
      "car vacuum",
      "car power inverter",
      "wiper",
      "detailing",
      "car mat",
      "tire",
      "ფარდაგების კომპლექტი",
      "საბურავი",
      "ძრავის ზეთი",
      "ტრანსმისიის ზეთი",
      "მანქანის დამცავი გადასაფარებელი",
      "ტორპედოს საპრიალებელი",
      "აკუმულატორი",
      "გადასაბმელი სადენები",
      "მოდულარი ჩაფხუტი",
      "მანქანის არომატიზატორი",
      "მანქანის დამტენი",
      "ტელეფონის დამჭერი",
      "მობილურის სამაგრი",
      "მანქანის მაგნიტური",
      "კომპრესორი",
      "ავტო მტვერსასრუტი",
    ],
    contextKeywords: ["automotive", "car accessories", "ავტო"],
    shopKeywords: ["avto", "auto", "car"],
    titleWeight: 92,
  },
  {
    slug: "cables-adapters",
    titleKeywords: [
      "dvi cable",
      "printer cable",
      "hdmi cable",
      "network cable",
      "ethernet cable",
      "patch cord",
      "cat5 utp",
      "audio adapter",
      "usb hub",
      "usb-c hub",
      "usb c hub",
      "type-c 7-in-1 hub",
      "type-c usb ჰაბი",
      "usb3.0 to rj-45 adapter",
      "usb-c to hdmi",
      "usb c to hdmi",
      "type-c to hdmi",
      "usb-c adapter",
      "usb c adapter",
      "hdmi switch",
      "hdmi splitter",
      "hdmi to rca converter",
      "digital av multiport adapter",
      "multiport adapter",
      "travel dock",
      "power adapter",
      "asus rog 65w adapter",
      "ac adapter",
      "usb-c to usb-c cable",
      "usb c to usb c cable",
      "usb-c to lightning cable",
      "usb-c to lightning",
      "usb c to lightning",
      "type-c to lightning",
      "charging cable",
      "micro-usb cable",
      "usb to micro-usb cable",
      "usb-c to usb-c",
      "usb c to usb c",
      "ethernet adapter",
      "sata adapter",
      "cable",
      "displayport cable",
      "pc adapter",
      "კაბელი",
      "ადაპტერი",
    ],
    negativeKeywords: ["phone cable", "iphone cable", "car charger", "magsafe", "power bank", "phone case", "headphone", "headset", "on-ear"],
    contextKeywords: ["cables", "adapters", "adapter", "cable"],
    titleWeight: 95,
  },
  {
    slug: "computer-accessories",
    titleKeywords: [
      "mouse pad",
      "mousepad",
      "keyboard",
      "mouse",
      "monitor stand",
      "desk mount",
      "display mount",
      "mounting arm",
      "laptop stand",
      "laptop bag",
      "ნოუთბუქის ჩანთა",
      "printer toner",
      "cartridge",
      "printer ink",
      "canon gi-",
      "genius nx-7015",
      "nx-7015",
      "wireless optical mouse",
      "wired usb combo",
      "wired combo",
      "logitech mk120",
      "logitech mk",
      "logitech m185",
      "gembird mus",
      "gembird kbs",
      "gembird kpd",
      "gembird kb-",
      "logitech mx keys",
      "card reader",
      "enclosure",
      "palm rest",
      "keychron",
      "magic trackpad",
      "კლავიატურა",
      "მაუსი",
    ],
    contextKeywords: ["pc accessory", "computer accessory", "peripheral"],
    titleWeight: 88,
  },
  {
    slug: "phone-accessories",
    titleKeywords: [
      "screen protector",
      "tempered glass",
      "privacy",
      "privacy for iphone",
      "ეკრანის დამცავი",
      "დამცავი",
      "glass pro",
      "privacy shield",
      "camera protector",
      "lens protector",
      "magsafe",
      "power bank",
      "canyon pb",
      "usb-c charger",
      "phone case",
      "iphone case",
      "hc pu",
      "hc silicone",
      "hard cover",
      "uniq hybrid magclick",
      "spigen",
      "skinarma",
      "uniq hybrid",
      "liquid air",
      "ultra hybrid",
      "magfit",
      "mag charge",
      "magclick",
      "lifepro",
      "clario",
      "lyden",
      "sonix",
      "saido",
      "phantom",
      "magma",
      "vigor",
      "deji",
      "startek",
      "iphone battery",
      "battery for iphone",
      "mobile holder plate",
      "magnetic plate",
      "case",
      "cover",
      "phone charger",
      "phone cable",
      "iphone cable",
      "charging micro",
      "wireless charger",
      "wireless charging station",
      "charger",
      "დამტენი",
      "ქეისი",
      "შუშა",
      "პაუერ ბანკი",
    ],
    negativeKeywords: [
      "ipad",
      "galaxy tab",
      "tablet",
      "ps5",
      "steam deck",
      "switch",
      "nintendo",
      "console",
      "handheld",
      "watch",
      "pixel watch",
      "samsung watch",
      "audio cable",
      "3.5mm",
      "female audio",
      "dual sim",
      "a075fd",
      "car charger",
      "pc case",
      "computer case",
      "console case",
      "nintendo case",
      "switch case",
      "laptop charger",
      "dvi cable",
      "printer cable",
      "hdmi switch",
      "audio adapter",
      "pc adapter",
      "network cable",
    ],
    contextKeywords: ["phone accessories", "mobile accessories", "ტელეფონის აქსესუარი"],
    titleKeywordGroups: [
      ["iphone", "battery"],
      ["iphone", "privacy"],
      ["iphone", "screen protector"],
      ["iphone", "ეკრანის დამცავი"],
      ["iphone", "დამცავი"],
      ["samsung galaxy", "spigen"],
      ["samsung galaxy", "magfit"],
      ["samsung galaxy", "uniq hybrid"],
      ["iphone", "skinarma"],
      ["iphone", "uniq hybrid"],
      ["iphone", "mag charge"],
      ["iphone", "magclick"],
      ["mobile", "holder", "plate"],
    ],
    shopKeywords: ["aksesuar", "accessor", "damteni", "case"],
    titleWeight: 88,
  },
  {
    slug: "laptops",
    titleKeywords: [
      "macbook",
      "laptop",
      "notebook",
      "ideapad",
      "thinkpad",
      "vivobook",
      "zenbook",
      "hp pavilion",
      "elitebook",
      "dell inspiron",
      "tuf",
      "omnibook",
      "aspire lite",
      "msi modern",
      "msi thin",
      "msi sword",
      "expertbook",
      "rog strix g16",
      "nitro v15",
      "lenovo yoga",
      "lenovo loq",
      "ლეპტოპი",
    ],
    negativeKeywords: ["laptop bag", "laptop stand", "laptop charger"],
    contextKeywords: ["portable computer", "leptopebi"],
    shopKeywords: ["laptop", "leptop"],
    titleWeight: 90,
  },
  {
    slug: "tablet-accessories",
    titleKeywords: [
      "ipad case",
      "ipad cover",
      "ipad flip cover",
      "ipad keyboard",
      "magic keyboard for ipad",
      "tablet case",
      "tablet cover",
      "galaxy tab case",
      "galaxy tab cover",
      "xiaomi pad case",
      "redmi pad case",
      "პლანშეტის ქეისი",
      "ტაბლეტის ქეისი",
    ],
    titleKeywordGroups: [
      ["ipad", "case"],
      ["ipad", "cover"],
      ["ipad", "flip", "cover"],
      ["ipad", "ქეისი"],
      ["ipad", "tempered glass"],
      ["ipad", "screen protector"],
      ["galaxy tab", "tempered glass"],
      ["galaxy tab", "screen protector"],
      ["galaxy tab", "case"],
      ["galaxy tab", "cover"],
      ["xiaomi pad", "case"],
      ["redmi pad", "case"],
      ["ipad", "keyboard"],
      ["skinarma", "ipad"],
    ],
    contextKeywords: ["tablet accessories", "ipad accessories"],
    titleWeight: 99,
  },
  {
    slug: "tablets",
    titleKeywords: [
      "ipad",
      "galaxy tab",
      "xiaomi pad",
      "redmi pad",
      "honor pad",
      "magicpad",
      "honor magicpad",
      "nubia pad",
      "oneplus pad",
      "matepad",
      "lenovo tab",
      "idea tab",
      "tablet",
      "ტაბლეტი",
    ],
    negativeKeywords: ["case", "cover", "screen protector", "tempered glass", "keyboard case", "tablet case", "ქეისი", "პლანშეტის ქეისი", "ტაბლეტის ქეისი"],
    contextKeywords: ["tablet", "tablets"],
    shopKeywords: ["tablet", "planchet"],
    titleWeight: 96,
  },
  {
    slug: "audio",
    titleKeywords: ["wireless earbuds", "wireless headphones", "mode ii", "5503abbg", "5503abkc", "ყურსასმენი", "უსადენო ყურსასმენი"],
    titleKeywordGroups: [
      ["honor x6", "5503"],
      ["mobile", "wireless", "headphone"],
      ["მობილური", "ყურსასმენი"],
    ],
    titleWeight: 98,
  },
  {
    slug: "mobiles",
    titleKeywords: [
      "iphone",
      "samsung galaxy",
      "redmi",
      "poco",
      "honor magic",
      "honor x",
      "honor",
      "samsung a16",
      "realme",
      "vivo",
      "oneplus",
      "nothing phone",
      "motorola",
      "moto g",
      "moto edge",
      "razr",
      "zte",
      "nubia",
      "hmd",
      "motorola moto",
      "pixel",
      "smartphone",
      "mobile phone",
      "dual sim",
      "მობილური",
      "ტელეფონი",
    ],
    negativeKeywords: [
      "case",
      "cover",
      "screen protector",
      "protector",
      "privacy",
      "ეკრანის დამცავი",
      "დამცავი",
      "glass",
      "cable",
      "adapter",
      "power bank",
      "magsafe",
      "magfit",
      "mag charge",
      "magclick",
      "liquid air",
      "ultra hybrid",
      "spigen",
      "skinarma",
      "uniq hybrid",
      "startek",
      "deji",
      "battery",
      "magnetic",
      "holder",
      "სამაგრი",
      "სამაგრის",
      "ფირფიტა",
      "strap",
      "buds",
      "earbuds",
      "headphone",
      "ყურსასმენი",
      "უსადენო ყურსასმენი",
      "5503abbg",
      "5503abkc",
      "watch",
      "tablet",
      "tv",
      "sound",
      "speaker",
      "shaver",
      "printer",
      "vacuum",
      "table",
      "treadmill",
      "bike",
      "mesh",
      "router",
      "ქეისი",
      "შუშა",
      "დამტენი",
      "კაბელი",
    ],
    titleKeywordGroups: [
      ["xiaomi", "gb"],
      ["xiaomii", "gb"],
      ["xiaomi", "64gb"],
      ["xiaomi", "128gb"],
      ["xiaomi", "256gb"],
      ["xiaomi", "512gb"],
      ["xiaomi", "1tb"],
      ["xiaomi", "lte"],
      ["xiaomi", "5g"],
      ["redmi", "gb"],
      ["poco", "gb"],
      ["oneplus", "gb"],
      ["nothing", "phone", "gb"],
      ["motorola", "gb"],
      ["moto", "gb"],
      ["razr", "gb"],
    ],
    contextKeywords: ["smartphones", "mobile phones"],
    shopKeywords: ["mobilurebi", "smartphone"],
    titleWeight: 86,
  },
  {
    slug: "wearables",
    titleKeywords: ["apple watch", "galaxy watch", "samsung watch", "pixel watch", "cmf watch", "amazfit", "huawei band", "smartwatch", "smart watch", "fitness band", "smart band", "watch strap", "watch film", "watch screen protector", "სმარტ საათი"],
    titleKeywordGroups: [
      ["watch", "screen", "film"],
      ["watch", "tempered", "glass"],
      ["watch", "protective", "film"],
    ],
    contextKeywords: ["wearable", "smart watch"],
    shopKeywords: ["smart-saat", "wearable"],
    titleWeight: 90,
  },
  {
    slug: "gaming",
    titleKeywords: ["playstation", "ps5", "xbox", "nintendo", "switch 2", "steam deck", "controller", "gamepad", "console", "console case", "handheld", "gaming headset", "gaming chair", "canyon gm", "logitech g", "legion m600", "hyperx", "razer", "ps5 game", "xbox game", "nintendo game", "გეიმინგ"],
    contextKeywords: ["gaming console", "games"],
    shopKeywords: ["gaming", "geiming"],
    titleWeight: 84,
  },
  {
    slug: "televisions",
    titleKeywords: ["smart tv", "oled tv", "qled", "led tv", "television", "fire tv stick", "lg tv", "samsung tv", "sony tv", "toshiba tv", "blaupunkt tv", "tcl tv", "vestel tv", "ტელევიზორი"],
    titleKeywordGroups: [
      ["xiaomi", "tv"],
      ["mini", "led"],
    ],
    contextKeywords: ["tv audio", "televizor"],
    shopKeywords: ["televizor", "tv"],
    titleWeight: 90,
  },
  {
    slug: "refrigerators",
    titleKeywords: ["refrigerator", "fridge", "freezer", "lg gr-", "moodup gr-", "vestel rs", "vestel rm", "midea mdrc", "bosch kur", "bosch kfi", "მაცივარი", "საყინულე"],
    contextKeywords: ["refrigeration"],
    titleWeight: 94,
  },
  {
    slug: "washing-machines",
    titleKeywords: ["washing machine", "washer dryer", "washer", "dryer", "midea mfk", "bosch wna", "bosch wnc", "bosch wls", "samsung wd", "vestel w6", "vestel w7", "სარეცხი მანქანა", "საშრობი"],
    negativeKeywords: ["hair dryer", "blow dryer", "ფენი"],
    contextKeywords: ["laundry"],
    titleWeight: 92,
  },
  {
    slug: "small-appliances",
    titleKeywords: [
      "coffee machine",
      "delonghi",
      "rivelia",
      "blender",
      "kettle",
      "toaster",
      "air fryer",
      "mixer",
      "iron",
      "braun is",
      "kenwood km",
      "kenwood fdp",
      "kenwood kvl",
      "kenwood khc",
      "bosch mums",
      "braun cg",
      "kitchenminis",
      "chopper",
      "spiralizer",
      "meat mincer",
      "citrus press",
      "lint remover",
      "mijia lint remover",
      "სამზარეულოს კომბაინი",
      "ყავის ელექტრო საფქვავი",
      "hair dryer",
      "ყავის აპარატი",
      "ბლენდერი",
      "ჩაიდანი",
      "ტოსტერი",
      "აეროგრილი",
      "მიქსერი",
      "უთო",
      "ფენი",
    ],
    negativeKeywords: ["coffee cup", "mug", "ჭიქა", "ფინჯანი", "nx-7015", "genius nx"],
    contextKeywords: ["small appliance"],
    titleWeight: 90,
  },
  {
    slug: "home-appliances",
    titleKeywords: [
      "dishwasher",
      "oven",
      "cooker",
      "microwave",
      "air conditioner",
      "heater",
      "standing fan",
      "smart standing fan",
      "fan pro",
      "vacuum cleaner",
      "wet dry vacuum",
      "truclean",
      "vacuum",
      "robot vacuum",
      "dreame x50",
      "bosch smv",
      "bosch sps",
      "bosch hxs",
      "purifier",
      "airforce modulo",
      "airforce f300",
      "გამწოვი",
      "karcher sc",
      "dyson wr01",
      "lg dfb",
      "samsung vc",
      "ჭურჭლის სარეცხი",
      "ღუმელი",
      "მიკროტალღური",
      "კონდიციონერი",
      "გამათბობელი",
      "მტვერსასრუტი",
    ],
    contextKeywords: ["domestic appliance", "home appliance"],
    titleWeight: 88,
  },
  {
    slug: "photo-video",
    titleKeywords: ["action camera", "camera", "webcam", "fujifilm instax", "ugreen cm778", "canon eos", "sony ilce", "sony ilme", "sony sel", "dji", "gopro", "digital photo frame", "on-camera microphone", "on camera microphone", "shotgun microphone", "lens", "tripod", "gimbal", "camera light", "კამერა", "შტატივი", "გიმბალი"],
    titleKeywordGroups: [
      ["photo", "printer"],
      ["portable", "photo", "printer"],
    ],
    contextKeywords: ["photo video", "photo equipment"],
    negativeKeywords: ["dash cam", "glass pro", "screen protector", "tempered glass", "camera protector", "lens protector"],
    titleWeight: 94,
  },
  {
    slug: "audio",
    titleKeywords: ["airpods", "earbuds", "buds", "redmi buds", "freebuds", "galaxy buds", "nothing ear", "jbl", "edifier", "klipsch", "soundcore", "crosley", "headphone", "headset", "on-ear", "in-ear", "speaker", "soundbar", "microphone", "turntable", "ყურსასმენი", "დინამიკი", "მიკროფონი"],
    titleKeywordGroups: [
      ["xiaomi", "sound"],
      ["sound", "outdoor"],
      ["sound", "pocket"],
    ],
    contextKeywords: ["audio"],
    shopKeywords: ["audio", "yursasmen"],
    titleWeight: 84,
  },
  {
    slug: "monitors",
    titleKeywords: ["gaming monitor", "office monitor", "monitor", "thinkvision", "acer nitro xf", "acer nitro vg", "acer ek251", "alienware aw", "asus rog strix 27", "philips 273", "dell u3425", "dell s2425", "benq gw", "msi g274f", "მონიტორი"],
    negativeKeywords: ["monitor stand", "desk mount", "display mount", "mounting arm"],
    contextKeywords: ["monitor", "display"],
    titleWeight: 92,
  },
  {
    slug: "computers",
    titleKeywords: [
      "desktop pc",
      "ssd",
      "ram",
      "gpu",
      "cpu",
      "motherboard",
      "router",
      "printer",
      "mesh system",
      "mesh wifi",
      "mesh wi-fi",
      "ac1200",
      "imac",
      "ddr4",
      "ddr5",
      "datatraveler",
      "crucial bx",
      "ecotank",
      "canon pixma",
      "wd purple",
      "external hdd",
      "kingston fury",
      "intel i7-",
      "zalman",
      "fsp ",
      "ee i7-",
      "ee i3-",
      "acemagic",
      "poe injector",
      "ups ",
      "როუტერი",
      "პრინტერი",
    ],
    contextKeywords: ["pc parts", "computer parts", "network"],
    shopKeywords: ["pc", "computer", "kompiuter", "monitor"],
    titleWeight: 78,
  },
  {
    slug: "furniture",
    titleKeywords: [
      "sofa",
      "chair",
      "table",
      "bed",
      "mattress",
      "wardrobe",
      "cabinet",
      "shelf",
      "desk",
      "armchair",
      "stool",
      "dresser",
      "couch",
      "დივანი",
      "სკამი",
      "მაგიდა",
      "საწოლი",
      "მატრასი",
      "კარადა",
      "თარო",
      "სამუშაო მაგიდა",
      "სავარძელი",
      "ტუმბო",
    ],
    titleKeywordGroups: [
      ["height", "adjustable", "table"],
      ["adjustable", "table"],
    ],
    negativeKeywords: FURNITURE_NEGATIVE_KEYWORDS,
    contextKeywords: ["furniture", "ავეჯი"],
    shopKeywords: ["furniture", "aveji"],
    titleWeight: 84,
    requiresTitleMatch: true,
  },
  {
    slug: "home-garden",
    titleKeywords: ["scent diffuser", "smart scent diffuser", "rainbow batteries", "aa batteries", "aaa batteries", "batteries"],
    titleWeight: 92,
  },
  {
    slug: "home-garden",
    titleKeywords: ["garden tool", "storage box", "lighting", "lamp", "home decor", "cleaning tool", "organizer", "extension cord", "smart wall switch", "broadlink", "garden hose", "soap dispenser", "წყლის მილი", "სარწყავი შლანგი", "საპნის დისპენსერი", "ელექტრო ხრახნდამჭერი", "ტორსული ხერხი", "დეკორატიული ღობე", "ხელსაწყო", "ბაღი", "განათება", "დეკორი", "ორგანიზერი"],
    contextKeywords: ["home garden", "cleaning"],
    titleWeight: 72,
  },
  {
    slug: "beauty",
    titleKeywords: ["beauty", "skincare", "skin care", "cosmetic", "perfume", "personal care", "face toner", "toner face", "ampoule", "ესენცია", "სახის შრატი", "სახის გელ-კრემი", "moisturizer", "დამატენიანებელი", "highlighting powder", "ჰაილაითერი", "foundation", "სახის ტონალური", "body lotion", "ტანის ლოსიონი", "წამწამები", "ბლაში", "ტუჩსაცხი", "სუნამო", "trimmer", "philips mg", "braun bg", "braun xt", "braun pl", "rowenta cv", "rowenta cf", "rowenta tn", "bodygroom", "multigroom", "multi groomer", "toothbrush", "oneblade", "supersonic", "airwrap", "airstyle", "dreame pocket", "hair styler", "shampoo", "შამპუნი", "თმის ცვილი", "თმის ბალზამი", "სახის გამწმენდი", "body retreat", "nail file", "glass file", "სილამაზე", "კოსმეტიკა", "პარფიუმ"],
    titleKeywordGroups: [
      ["electric", "shaver"],
      ["xiaomi", "shaver"],
    ],
    titleWeight: 74,
  },
  {
    slug: "sport",
    titleKeywords: ["sport", "fitness", "bicycle", "scooter", "ekinekt", "სავარჯიშო რეზინი", "სპორტ", "ფიტნეს"],
    titleWeight: 72,
  },
  {
    slug: "sport",
    titleKeywords: [],
    titleKeywordGroups: [
      ["walkingpad"],
      ["treadmill"],
      ["spinning", "bike"],
    ],
    titleWeight: 92,
  },
  {
    slug: "kids",
    titleKeywords: ["kids", "baby", "child", "toy", "stroller", "lego", "hasbro", "revell", "magic blocks", "carter's", "ფაზლი", "მძივების ნაკრები", "რბილი ბურთი", "ტყუპების ეტლი", "საწოლ-მანეჟი", "სამაგიდო თამაში", "საბავშვო", "საბაშვო", "ბავშვ", "სათამაშო"],
    titleWeight: 72,
  },
  {
    slug: "pets",
    titleKeywords: ["petsuper", "pet feeder", "pet water", "pet dispenser", "pet supplies", "pet leash", "dog leash", "cat leash", "leash nylon", "dog waste", "ძაღლის", "ცხოველ"],
    titleWeight: 90,
  },
  {
    slug: "books-stationery",
    titleKeywords: ["book", "stationery", "notebook", "marker", "pencil", "paper", "ფლომასტერ", "ფერადი ფანქარ", "სახაზავი", "წიგნ", "საკანცელარიო", "ფურც"],
    titleWeight: 78,
  },
];

// Adapters may pass raw breadcrumb/path fragments. These hints must never beat a strong title rule.
export const SHOP_CATEGORY_MAPPING: Record<string, Record<string, FasmetriCategorySlug>> = {
  alta: {
    laptops: "laptops",
    smartphones: "mobiles",
    televisions: "televisions",
    appliances: "home-appliances",
  },
  ee: {
    kompiuterebi: "computers",
    leptopebi: "laptops",
    mobilurebi: "mobiles",
    televizorebi: "televisions",
  },
  extra: {
    kitchenware: "kitchen-dishes",
    furniture: "furniture",
    mobiles: "mobiles",
  },
  pcshop: {
    laptop: "laptops",
    monitor: "monitors",
    network: "computers",
    printer: "computers",
  },
  zoommer: {
    leptopebi: "laptops",
    mobilurebi: "mobiles",
    monitorebi: "monitors",
    smartsaatebi: "wearables",
    tabletebi: "tablets",
    yursasmenebi: "audio",
  },
};
