export const PRODUCT_NOISE_WORDS = [
  "მობილური ტელეფონი",
  "ტელეფონი",
  "სმარტფონი",
  "ლეპტოპი",
  "ტელევიზორი",
  "ყურსასმენი",
  "სმარტ საათი",
  "სმარტ ვოჩი",
  "სმარტ სახლი",
  "ახალი",
  "ოფიციალური",
  "გარანტია",
  "ფასდაკლება",
  "აქცია",
  "mobile phone",
  "smartphone",
  "official",
  "warranty",
  "new",
  "sale",
  "discount",
  "unlocked",
  "global version",
  "dual sim",
] as const;

export const TEXT_ALIASES: ReadonlyArray<readonly [RegExp, string]> = [
  // SIM types (before single-word "esim" catch)
  [/\be[\s-]?sim\s+only\b/gi, "esim_only"],
  [/\be[\s-]?sim\b/gi, "esim"],
  [/\bdual[\s-]?sim\b/gi, "dual_sim"],
  [/\bphysical[\s-]?sim\b/gi, "physical_sim"],
  [/\bnano[\s-]?sim\b/gi, "physical_sim"],
  // Connectivity
  [/\bwi[\s-]?fi\b/gi, "wifi"],
  // Model suffix normalization
  [/\bpro[\s-]?max\b/gi, "pro max"],
  // Memory notation
  [/\b(\d{1,2})\s*\/\s*(\d{2,4})\s*gb\b/gi, "$1/$2gb"],
  [/\b(\d{1,2})\s*\/\s*(\d{2,4})\b/gi, "$1/$2"],
  // Multi-word colors — must appear BEFORE single-word aliases
  [/\bblack[\s-]?titanium\b/gi, "black_titanium"],
  [/\bblue[\s-]?titanium\b/gi, "blue_titanium"],
  [/\bnatural[\s-]?titanium\b/gi, "natural_titanium"],
  [/\bdesert[\s-]?titanium\b/gi, "desert_titanium"],
  [/\bwhite[\s-]?titanium\b/gi, "white_titanium"],
  [/\bpink[\s-]?titanium\b/gi, "pink_titanium"],
  [/\bcosmic[\s-]?orange\b/gi, "cosmic_orange"],
  [/\bspace[\s-]?black\b/gi, "space_black"],
  [/\bspace[\s-]?gray\b/gi, "space_gray"],
  [/\brose[\s-]?gold\b/gi, "rose_gold"],
  [/\bsky[\s-]?blue\b/gi, "sky_blue"],
  [/\bmidnight[\s-]?blue\b/gi, "blue"],
  [/\bmidnight[\s-]?green\b/gi, "green"],
  [/\bmidnight[\s-]?black\b/gi, "black"],
  [/\baurora[\s-]?green\b/gi, "green"],
  [/\blime[\s-]?green\b/gi, "green"],
  [/\bsea[\s-]?green\b/gi, "green"],
  [/\bsage[\s-]?green\b/gi, "green"],
  [/\bforest[\s-]?green\b/gi, "green"],
  [/\bnavy[\s-]?blue\b/gi, "blue"],
  [/\bice[\s-]?blue\b/gi, "blue"],
  [/\bocean[\s-]?blue\b/gi, "blue"],
  [/\bsteel[\s-]?blue\b/gi, "blue"],
  [/\bcoral[\s-]?red\b/gi, "coral"],
  [/\bchampagne[\s-]?gold\b/gi, "gold"],
  [/\bsunset[\s-]?gold\b/gi, "gold"],
  [/\bsunrise[\s-]?gold\b/gi, "gold"],
  [/\bsand[\s-]?gold\b/gi, "gold"],
  [/\bdreamy[\s-]?purple\b/gi, "purple"],
  [/\bpantone[\s-]?hematite\b/gi, "hematite"],
  [/\bsporting[\s-]?green\b/gi, "green"],
  [/\bmartini[\s-]?olive\b/gi, "olive"],
  [/\barctic[\s-]?seal\b/gi, "gray"],
  [/\blaurel[\s-]?oak\b/gi, "green"],
  // Apple/Samsung phone colors
  [/\bultramarine\b/gi, "blue"],
  [/\bsage\b/gi, "sage"],
  [/\bpowder\s*blue\b/gi, "blue"],
  [/\bmist\s*blue\b/gi, "blue"],
  [/\bdeep\s*blue\b/gi, "blue"],
  [/\bpetrol\b/gi, "blue"],
  [/\bvibrant\s*yellow\b/gi, "yellow"],
  [/\blight\s*green\b/gi, "green"],
  [/\bgraygreen\b/gi, "green"],
  [/\bphantom\s*black\b/gi, "black"],
  [/\bphantom\s*white\b/gi, "white"],
  [/\bphantom\s*gray\b/gi, "gray"],
  [/\bphantom\s*violet\b/gi, "violet"],
  [/\bcozy\s*cream\b/gi, "cream"],
  [/\bcream\s*beige\b/gi, "beige"],
  [/\bmatcha\b/gi, "green"],
  [/\bpinkgold\b/gi, "rose_gold"],
  [/\bblossom\b/gi, "pink"],
  [/\bclover\b/gi, "green"],
  [/\bfern\b/gi, "green"],
  [/\bskyline\s*blue\b/gi, "blue"],
  // Single-word fantasy/marketing colors → canonical
  [/\btapestry\b/gi, "gray"],
  [/\bzephyr\b/gi, "blue"],
  [/\bnile\b/gi, "green"],
  [/\bgrape\b/gi, "purple"],
  [/\bjade\b/gi, "green"],
  [/\bcharcoal\b/gi, "black"],
  [/\bslate\b/gi, "gray"],
  [/\bsteel\b/gi, "gray"],
  [/\bivory\b/gi, "white"],
  [/\bcream\b/gi, "cream"],
  [/\btan\b/gi, "beige"],
  [/\bmaroon\b/gi, "burgundy"],
  // Georgian color words
  [/იასამნისფერი/gi, "purple"],
  [/მეწამული/gi, "purple"],
  [/შავი/gi, "black"],
  [/თეთრი/gi, "white"],
  [/ვერცხლისფერი/gi, "silver"],
  [/ლურჯი/gi, "blue"],
  [/მწვანე/gi, "green"],
  [/ნარინჯისფერი/gi, "orange"],
  [/ოქროსფერი/gi, "gold"],
  [/ოქრო(?!სფერი)/gi, "gold"],
  [/წითელი/gi, "red"],
  [/ყვითელი/gi, "yellow"],
  [/ვარდისფერი/gi, "pink"],
  [/ყავისფერი/gi, "brown"],
  [/ფირუზისფერი/gi, "turquoise"],
  [/ნაცრისფერი/gi, "gray"],
  [/ვიოლეტური/gi, "violet"],
  [/კრემისფერი/gi, "cream"],
  [/ბეჟი/gi, "beige"],
  [/ბორდო/gi, "burgundy"],
  [/ცისფერი/gi, "sky_blue"],
];

export const COLOR_ALIASES: Record<string, string> = {
  // Titanium colorways (iPhone 15/16/17)
  "black titanium": "black_titanium",
  black_titanium: "black_titanium",
  "blue titanium": "blue_titanium",
  blue_titanium: "blue_titanium",
  "natural titanium": "natural_titanium",
  natural_titanium: "natural_titanium",
  "desert titanium": "desert_titanium",
  desert_titanium: "desert_titanium",
  "white titanium": "white_titanium",
  white_titanium: "white_titanium",
  "pink titanium": "pink_titanium",
  pink_titanium: "pink_titanium",
  // Named colorways
  "cosmic orange": "cosmic_orange",
  cosmic_orange: "cosmic_orange",
  "space black": "space_black",
  space_black: "space_black",
  "space gray": "space_gray",
  space_gray: "space_gray",
  "rose gold": "rose_gold",
  rose_gold: "rose_gold",
  "sky blue": "sky_blue",
  sky_blue: "sky_blue",
  // Standard colors
  graphite: "graphite",
  hematite: "hematite",
  olive: "olive",
  silver: "silver",
  black: "black",
  white: "white",
  blue: "blue",
  green: "green",
  orange: "orange",
  gold: "gold",
  gray: "gray",
  grey: "gray",
  purple: "purple",
  pink: "pink",
  red: "red",
  yellow: "yellow",
  violet: "violet",
  lavender: "lavender",
  coral: "coral",
  cream: "cream",
  beige: "beige",
  burgundy: "burgundy",
  brown: "brown",
  teal: "teal",
  cyan: "cyan",
  turquoise: "turquoise",
  mint: "mint",
  lime: "lime",
  // Apple Watch colors
  starlight: "starlight",
  midnight: "midnight",
  // Apple/Samsung phone fantasy colors
  ultramarine: "blue",
  sage: "sage",
  "mist blue": "blue",
  mist_blue: "blue",
  "deep blue": "blue",
  deep_blue: "blue",
  "powder blue": "blue",
  powder_blue: "blue",
  "phantom black": "black",
  phantom_black: "black",
  "phantom white": "white",
  phantom_white: "white",
  "phantom gray": "gray",
  phantom_gray: "gray",
  "phantom violet": "violet",
  phantom_violet: "violet",
  matcha: "green",
  blossom: "pink",
  clover: "green",
  fern: "green",
  // Fantasy/marketing → canonical (duplicates TEXT_ALIASES for direct lookups)
  grape: "purple",
  "dreamy purple": "purple",
  jade: "green",
  charcoal: "black",
  slate: "gray",
  steel: "gray",
  ivory: "white",
  tan: "beige",
  maroon: "burgundy",
  "pantone hematite": "hematite",
  "sporting green": "green",
  "arctic seal": "gray",
  "laurel oak": "green",
  tapestry: "gray",
  zephyr: "blue",
  nile: "green",
  // Georgian color words (fallback if TEXT_ALIASES already ran, these become no-ops)
  შავი: "black",
  თეთრი: "white",
  ვერცხლისფერი: "silver",
  ლურჯი: "blue",
  მწვანე: "green",
  ნარინჯისფერი: "orange",
  ოქროსფერი: "gold",
  იასამნისფერი: "purple",
  მეწამული: "purple",
  წითელი: "red",
  ყვითელი: "yellow",
  ვარდისფერი: "pink",
  ყავისფერი: "brown",
  ფირუზისფერი: "turquoise",
  ნაცრისფერი: "gray",
  ვიოლეტური: "violet",
  კრემისფერი: "cream",
  ბეჟი: "beige",
  ბორდო: "burgundy",
  ცისფერი: "sky_blue",
};

export const MODEL_ALIASES: ReadonlyArray<readonly [RegExp, string]> = [
  // iPhone 17 series (explicit aliases for critical match cases)
  [/\b(?:apple\s+)?iphone\s+17\s+pro\s+max\b/i, "iphone_17_pro_max"],
  [/\b(?:apple\s+)?iphone\s+17\s+pro\b/i, "iphone_17_pro"],
  [/\b(?:apple\s+)?iphone\s+17e?\s+plus\b/i, "iphone_17_plus"],
  // iPhone 16 series
  [/\b(?:apple\s+)?iphone\s+16\s+pro\s+max\b/i, "iphone_16_pro_max"],
  [/\b(?:apple\s+)?iphone\s+16\s+pro\b/i, "iphone_16_pro"],
  [/\b(?:apple\s+)?iphone\s+16\s+plus\b/i, "iphone_16_plus"],
  // Xiaomi/Redmi 14C (both "Xiaomi 14C" and "Redmi 14C" forms)
  [/\b(?:xiaomi\s+)?redmi\s+14c\b/i, "redmi_14c"],
  [/\bxiaomi\s+14c\b/i, "redmi_14c"],
  // Samsung Galaxy S26 series
  [/\b(?:samsung\s+)?galaxy\s+s26\s+ultra\b/i, "galaxy_s26_ultra"],
  [/\b(?:samsung\s+)?galaxy\s+s26\s+plus\b/i, "galaxy_s26_plus"],
  [/\b(?:samsung\s+)?galaxy\s+s26\b/i, "galaxy_s26"],
  // Samsung Galaxy S25 series
  [/\b(?:samsung\s+)?galaxy\s+s25\s+ultra\b/i, "galaxy_s25_ultra"],
  [/\b(?:samsung\s+)?galaxy\s+s25\s+plus\b/i, "galaxy_s25_plus"],
  [/\b(?:samsung\s+)?galaxy\s+s25\b/i, "galaxy_s25"],
];
