export const PRODUCT_NOISE_WORDS = [
  "მობილური ტელეფონი",
  "ტელეფონი",
  "სმარტფონი",
  "ახალი",
  "ოფიციალური",
  "გარანტია",
  "ფასდაკლება",
  "აქცია",
  "mobile phone",
  "smartphone",
  "official",
  "warranty",
  "new",
  "sale",
  "discount",
  "unlocked",
  "global version",
] as const;

export const TEXT_ALIASES: ReadonlyArray<readonly [RegExp, string]> = [
  [/\be[\s-]?sim\s+only\b/gi, "esim_only"],
  [/\be[\s-]?sim\b/gi, "esim"],
  [/\bdual[\s-]?sim\b/gi, "dual_sim"],
  [/\bphysical[\s-]?sim\b/gi, "physical_sim"],
  [/\bnano[\s-]?sim\b/gi, "physical_sim"],
  [/\bwi[\s-]?fi\b/gi, "wifi"],
  [/\bpro[\s-]?max\b/gi, "pro max"],
  [/\b(\d{1,2})\s*\/\s*(\d{2,4})\s*gb\b/gi, "$1/$2gb"],
  [/\b(\d{1,2})\s*\/\s*(\d{2,4})\b/gi, "$1/$2"],
  [/\bblack[\s-]?titanium\b/gi, "black_titanium"],
  [/\bblue[\s-]?titanium\b/gi, "blue_titanium"],
  [/\bnatural[\s-]?titanium\b/gi, "natural_titanium"],
  [/\bcosmic[\s-]?orange\b/gi, "cosmic_orange"],
  [/\bspace[\s-]?black\b/gi, "space_black"],
  [/\bdreamy[\s-]?purple\b/gi, "purple"],
  [/\bpantone[\s-]?hematite\b/gi, "hematite"],
  [/\bsporting[\s-]?green\b/gi, "green"],
  [/\bmartini[\s-]?olive\b/gi, "olive"],
  [/\barctic[\s-]?seal\b/gi, "gray"],
  [/\blaurel[\s-]?oak\b/gi, "green"],
  [/\btapestry\b/gi, "gray"],
  [/\bzephyr\b/gi, "blue"],
  [/\bnile\b/gi, "green"],
  [/\bgrape\b/gi, "purple"],
  [/იასამნისფერი/gi, "purple"],
  [/მეწამული/gi, "purple"],
  [/შავი/gi, "black"],
  [/თეთრი/gi, "white"],
  [/ვერცხლისფერი/gi, "silver"],
  [/ლურჯი/gi, "blue"],
  [/მწვანე/gi, "green"],
  [/ნარინჯისფერი/gi, "orange"],
  [/ოქროსფერი/gi, "gold"],
];

export const COLOR_ALIASES: Record<string, string> = {
  "black titanium": "black_titanium",
  black_titanium: "black_titanium",
  "blue titanium": "blue_titanium",
  blue_titanium: "blue_titanium",
  "natural titanium": "natural_titanium",
  natural_titanium: "natural_titanium",
  "cosmic orange": "cosmic_orange",
  cosmic_orange: "cosmic_orange",
  "space black": "space_black",
  space_black: "space_black",
  graphite: "graphite",
  silver: "silver",
  black: "black",
  white: "white",
  blue: "blue",
  green: "green",
  orange: "orange",
  gold: "gold",
  gray: "gray",
  grey: "gray",
  purple: "purple",
  pink: "pink",
  grape: "purple",
  "dreamy purple": "purple",
  hematite: "hematite",
  "pantone hematite": "hematite",
  olive: "olive",
  "martini olive": "olive",
  "sporting green": "green",
  "arctic seal": "gray",
  "laurel oak": "green",
  tapestry: "gray",
  zephyr: "blue",
  nile: "green",
  შავი: "black",
  თეთრი: "white",
  ვერცხლისფერი: "silver",
  ლურჯი: "blue",
  მწვანე: "green",
  ნარინჯისფერი: "orange",
  ოქროსფერი: "gold",
  იასამნისფერი: "purple",
  მეწამული: "purple",
};

export const MODEL_ALIASES: ReadonlyArray<readonly [RegExp, string]> = [
  [/\b(?:apple\s+)?iphone\s+17\s+pro\s+max\b/i, "iphone_17_pro_max"],
  [/\b(?:apple\s+)?iphone\s+17\s+pro\b/i, "iphone_17_pro"],
  [/\b(?:xiaomi\s+)?redmi\s+14c\b/i, "redmi_14c"],
  [/\bxiaomi\s+14c\b/i, "redmi_14c"],
];
