import assert from "node:assert/strict";
import { categorizeProduct } from "../src/lib/categorizeProduct";

const cases = [
  ["Apple iPhone 17 Pro Max 256GB Cosmic Orange", "mobiles"],
  ["Samsung Galaxy A07 4GB 64GB Green", "mobiles"],
  ["Samsung Galaxy A07 A075FD Dual Sim 4/128GB Black With Charger", "mobiles"],
  ["Samsung A16 8GB/256GB Gray SM-A165FZAICAU", "mobiles"],
  ["Xiaomi Poco F8 Ultra 5G 16/512GB Black", "mobiles"],
  ["HONOR 600 12GB 256GB Black", "mobiles"],
  ["Motorola Moto G86 5G 8/256GB Pink", "mobiles"],
  ["Xiaomi 14C 6GB/128GB Blue", "mobiles"],
  ["Xiaomi Redmi Note 15 Pro 5G 8/256GB Blue", "mobiles"],
  ["Xiaomi Pad 8 Pro 8/256GB Wi-Fi Green", "tablets"],
  ["Xiaomi Redmi Pad 2 Pro With Keyboard 8/256GB Wi-Fi Graphite", "tablets"],
  ["Samsung SM-X520 Galaxy Tab S10 FE 8/128GB Wi-Fi Blue", "tablets"],
  ["HUAWEI MatePad 11.5 8GB 256GB Space Gray", "tablets"],
  ["OnePlus Pad Go 2 8/256GB LTE Shadow Black", "tablets"],
  ["NILLKIN Apple iPad 10 პლანშეტის ქეისი", "tablet-accessories"],
  ["Apple Magic Keyboard for iPad Air 11-inch MDFV4RS/A White", "tablet-accessories"],
  ["Glass Pro+ Full Screen Tempered Glass Apple iPad Air 13 2026", "tablet-accessories"],
  ["Glass Pro+ Full Screen Tempered Glass Samsung X400 Galaxy Tab S10 Lite", "tablet-accessories"],
  ["Skinarma Spunk Apple Ipad Mini A17 Pro Pewter Green", "tablet-accessories"],
  ["Ovose Flip Cover Apple iPad Air 11 Inch 2026 Black", "tablet-accessories"],
  ["Ovose Flip Cover Samsung X133 Galaxy Tab A11 Black", "tablet-accessories"],
  ["USPA HC PU Smooth Embroidered USA Flag Big DH iPhone 17 Pro Max", "phone-accessories"],
  ["Spigen Samsung Galaxy S26 Ultra Screen Protector", "phone-accessories"],
  ["3D Privacy For iPhone 14 Pro ეკრანის დამცავი", "phone-accessories"],
  ["Spigen Liquid Air Magfit For Samsung Galaxy S26 Ultra ACS10675 Marble Gray", "phone-accessories"],
  ["Skinarma Sonix Mag Charge Apple iPhone 17 Pro Max Stone", "phone-accessories"],
  ["Uniq Hybrid Magclick Charging Clario Apple iPhone 17 Pro Lucent Clear", "phone-accessories"],
  ["STARTEK iPhone 12 Mini mobile screen protector", "phone-accessories"],
  ["DEJI iPhone 7 battery 1960mAh", "phone-accessories"],
  ["Glass Pro+ Eagle Eye Camera Pro For Apple iPhone 17 Pro Max Black", "phone-accessories"],
  ["Green Lion 9H Privacy Shield S26 Ultra GN9HPVS26ULBK", "phone-accessories"],
  ["Canyon PB - 301/CNE-CPB301B", "phone-accessories"],
  ["HOCO X58 Airy silicone charging Micro red/744524", "phone-accessories"],
  ["Samsung Galaxy A07 A075FD Dual Sim 4/64GB Green With Charger", "mobiles"],
  ["Belkin RockStar 3.5mm Audio Cable With USB-C Connector F7U079bt03-BLK Black", "cables-adapters"],
  ["Ugreen USB-C Male to 2x 3.5mm Female Audio Cable 25cm 30732 Space Grey", "cables-adapters"],
  ["მანქანის მაგნიტური მობილურის სამაგრის ფირფიტა", "auto-accessories"],
  ["Gembird USB-C to HDMI Adapter", "cables-adapters"],
  ["Apple USB-C Digital AV Multiport Adapter (MW5M3ZM/A)", "cables-adapters"],
  ["Gembird Type-C to HDMI + DP Adapter", "cables-adapters"],
  ["Gembird USB Type-C to SATA Adapter", "cables-adapters"],
  ["Gembird HDMI Splitter 2 Ports", "cables-adapters"],
  ["VENTION AEEB0 HDMI to RCA Converter Black Metal Type", "cables-adapters"],
  ["Hoco S51 Extreme PD USB Type-C to Lightning Black", "cables-adapters"],
  ["Baseus Unbreakable USB-C to USB-C 2m Black/White", "cables-adapters"],
  ["VENTION USB-C To 100M Ethernet Adapter", "cables-adapters"],
  ["Belkin Boostcharge PRO Flex USB-C to Lightning 1M Black", "cables-adapters"],
  ["Lenovo 65W USB-C AC Adapter", "cables-adapters"],
  ["Anker USB Type-C 7-in-1 Hub Grey", "cables-adapters"],
  ["VENTION CHNBB Type-C USB ჰაბი", "cables-adapters"],
  ["HP 150 Wired USB Combo Black", "computer-accessories"],
  ["HP Renew Business 14 Laptop Bag Black", "computer-accessories"],
  ["Logitech MK120 Wired Combo Black", "computer-accessories"],
  ["Gembird MUSW-4B-05 Wireless Black", "computer-accessories"],
  ["Gembird Compatct USB 3.0 Card Reader", "computer-accessories"],
  ["KEYCHRON K4 PALM REST მაჯის საყრდენი", "computer-accessories"],
  ["Redmi Buds 6 Pro Wireless Earbuds", "audio"],
  ["HONOR X6 Purple/5503ABKC", "audio"],
  ["HONOR X6 White/5503ABBG", "audio"],
  ["MODE II მობილური ტელეფონის უსადენო ყურსასმენი", "audio"],
  ["Gembird BHP-ANC-01 Wireless On-Ear Black", "audio"],
  ["Bloody G521 Cable On-ear Black", "audio"],
  ["Gembird MHS-EP-001 Wired In-ear Black", "audio"],
  ["JBL Boombox 4 Blue", "audio"],
  ["Nothing EAR 3 White", "audio"],
  ["Edifier S300 Black Walnut", "audio"],
  ["Anker Soundcore AeroFit 2 Blue", "audio"],
  ["Crosley Cruiser Plus Turntable Navy", "audio"],
  ["SONY Shotgun Microphone ECM-G1//Z SYU", "photo-video"],
  ["BOYA BY-MM1 On-Camera Microphone Black", "photo-video"],
  ["Canon EOS R6 MARK III V2.4 24-105mm STM Black", "photo-video"],
  ["Sony SEL50F14GM/JSYX Black", "photo-video"],
  ["DJI Mini 5 Pro Propeller Set CCW", "photo-video"],
  ["UGREEN CM778 Black/35626", "photo-video"],
  ["SONY ILME-FX30B/QCEC", "photo-video"],
  ["Xiaomi Portable Photo Printer Pro White", "photo-video"],
  ["Apple MacBook Air 13 M4 256GB", "laptops"],
  ["HP OmniBook 7 16-ay0005ci Intel Core Ultra", "laptops"],
  ["HP EliteBook Ultra G1i 14", "laptops"],
  ["Lenovo LOQ 15IRX9/83DV00YLRK", "laptops"],
  ["PlayStation 5 Slim Console", "gaming"],
  ["DOBE PS5 Handheld Silicone Protective Case TP5-3555 Red/Blue", "gaming"],
  ["DOBE Steam Deck Silicone Protective Cover TY-2836 Black", "gaming"],
  ["DOBE Switch 2 Console Silicone Case TNS-3158 Red", "gaming"],
  ["DOBE Switch 2 HD Tempered Glass 2pcs TNS-3166", "gaming"],
  ["Canyon GM-636/CND-SGM636W White", "gaming"],
  ["DOBE Switch 2 Charging Dock TNS-3171 Black", "gaming"],
  ["RAZER Mini 61key Purple Switch Black", "gaming"],
  ["Lenovo Legion M600s Wireless Black", "gaming"],
  ["Coffee Mug 350ml", "kitchen-dishes"],
  ["DeLonghi Rivelia EXAM440.55.G", "small-appliances"],
  ["Xiaomi Mijia Lint Remover 2 White", "small-appliances"],
  ["MIDEA MFK03D105B/S", "washing-machines"],
  ["BOSCH WNA25401ME White", "washing-machines"],
  ["Samsung WD18DB8995BZLD", "washing-machines"],
  ["BOSCH WNC254A0ME", "washing-machines"],
  ["VESTEL W710T1DS", "washing-machines"],
  ["LG GR-X267CQEW.AMCQMER", "refrigerators"],
  ["LG MoodUP GR-A34FDMKJ.ANNQGCC", "refrigerators"],
  ["BOSCH KUR21VFE0", "refrigerators"],
  ["BOSCH KFI96AXEA", "refrigerators"],
  ["PHILIPS MG5940/15", "beauty"],
  ["Dyson Airwrap HS08 ID Complete Long Ceramic Patina", "beauty"],
  ["IL SALONE ქერტლის საწინააღმდეგო შამპუნი", "beauty"],
  ["Golden Rose სახის გამწმენდი სითხე", "beauty"],
  ["GR MATTE PERFECTION FOUNDATION სახის ტონალური", "beauty"],
  ["Victoria's Secret ტანის ლოსიონი", "beauty"],
  ["FARMSTAY SYN-AKE REVITALIZING AMPOULE სახის შრატი", "beauty"],
  ["Philips Toothbrush HX3601/01 White", "beauty"],
  ["Philips OneBlade Replacement Blade 2 Pack QP220/51", "beauty"],
  ["Dyson HD16 Supersonic Nural Strawberry/Rose", "beauty"],
  ["ROWENTA CV1831F0", "beauty"],
  ["ROWENTA TN911LF0", "beauty"],
  ["ROWENTA CF9550F0", "beauty"],
  ["Xiaomi Electric Shaver S200 Grey", "beauty"],
  ["Philips Bodygroom BG7470/15 Black", "beauty"],
  ["BRAUN IS2577VI", "small-appliances"],
  ["Genius NX-7015 Wireless Iron Gray", "computer-accessories"],
  ["Canon GI-46 Cyan Printer Ink 135ml", "computer-accessories"],
  ["Canon GI-41 Yellow Ink 70ml", "computer-accessories"],
  ["Acer Nitro XF240YM3/UM.QX0EE.315 Black", "monitors"],
  ["Acer EK251QP6BI 25 FHD IPS Black", "monitors"],
  ["Acer EKinekt BD 3", "sport"],
  ["Xiaomi Kingsmith WalkingPad Treadmill MX16+ Black", "sport"],
  ["Xiaomi Kingsmith Spinning bike PB08S Black", "sport"],
  ["TCL TV 55P7K Black", "televisions"],
  ["Amazon Fire TV Stick 4K 2nd Gen Black", "televisions"],
  ["Xiaomi TV S Pro Mini led 55 2026 Black", "televisions"],
  ["Dreame X50 Ultra Black RLX85CE-4 Robot Vacuum", "home-appliances"],
  ["Xiaomi Truclean W30 Pro Wet Dry Vacuum", "home-appliances"],
  ["Xiaomi Smart Standing Fan Pro Slim White", "home-appliances"],
  ["AIRFORCE MODULO PLUS CCMODP52002", "home-appliances"],
  ["Dyson Purifier Hot+Cool HP1 White/Silver", "home-appliances"],
  ["KARCHER SC 3 Deluxe/1.513-430.0", "home-appliances"],
  ["Dyson WR01 WashG1 Bk/Bu", "home-appliances"],
  ["BOSCH HXS59AI21Q", "home-appliances"],
  ["LG DFB425FP.APZPARA", "home-appliances"],
  ["Samsung VC21K5170HG/EV", "home-appliances"],
  ["Kenwood KMX760AGD Stand Mixer", "small-appliances"],
  ["BOSCH MUMS6ZS17", "small-appliances"],
  ["BRAUN CG7020 გრილი", "small-appliances"],
  ["WMF KITCHENminis Chopper", "small-appliances"],
  ["WMF Profi Plus Meat Mincer", "small-appliances"],
  ["Russell Hobbs სამზარეულოს კომბაინი", "small-appliances"],
  ["Stelton ყავის ელექტრო საფქვავი", "small-appliances"],
  ["Petsuper Smart Pet Feeder PF02-2 White", "pets"],
  ["FLAMINGO ძაღლის ფეკალიების პარკი", "pets"],
  ["Hasbro პეპა გოჭის სკოლის შენობა", "kids"],
  ["Magic Blocks - Hello Kitty", "kids"],
  ["KS Games სამაგიდო თამაში, რა ვარ მე?", "kids"],
  ["LORELLI ტყუპების ეტლი DUO", "kids"],
  ["ToyColor MAGIC CHANGER ფლომასტერის ნაკრები", "books-stationery"],
  ["FITT IDRO GREEN 1/2 25m სარწყავი შლანგი", "home-garden"],
  ["MANAMO საპნის დისპენსერი", "home-garden"],
  ["Aqara Smart Wall Switch H1 EU", "home-garden"],
  ["Xiaomi Smart Scent Diffuser White", "home-garden"],
  ["Xiaomi AAA Rainbow Batteries 10 Count", "home-garden"],
  ["Xiaomi AA Rainbow Batteries 10 Count", "home-garden"],
  ["2E 20მ წყლის მილი", "home-garden"],
  ["ავტომობილის ფარდაგების კომპლექტი, რეზინის", "auto-accessories"],
  ["LINGLONG GRIP MASTER C/S 255/50R19 ზაფხულის საბურავი", "auto-accessories"],
  ["QUAX 5W-20 ძრავის ზეთი 1 ლ", "auto-accessories"],
  ["Vaico ATF 5ლ ტრანსმისიის ზეთი", "auto-accessories"],
  ["TAKASAKI მანქანის დამცავი გადასაფარებელი", "auto-accessories"],
  ["Staedtler 12ც ფერადი ფანქარები", "books-stationery"],
  ["KITE K24-090-2 სახაზავი", "books-stationery"],
  ["OLLIN Professional 250მლ თმის ბალზამი", "beauty"],
  ["KISS FALSCARA წამწამები ხელოვნური", "beauty"],
  ["Dior Rouge Blush ბლაში", "beauty"],
  ["BENQ GW2490/9H.LLSLB.QBE", "monitors"],
  ["MSI G274F (9S6-3CC2CH-054)", "monitors"],
  ["ACEMAGIC K1 i5-12600H 16GB/512GB", "computers"],
  ["Logitech MX Keys Mini Graphite", "computer-accessories"],
  ["Gembird Car power inverter 12V/500W", "auto-accessories"],
  ["Nothing CMF Watch Pro 2 Blue", "wearables"],
  ["Google Pixel Watch 3 45mm Wi-Fi Matte Hazel Case with Hazel Active Band", "wearables"],
  ["Glass Pro+ Full Screen Film Samsung Watch 8 40MM Black", "wearables"],
  ["Xiaomi Sound Outdoor 30W Green", "audio"],
  ["Xiaomi Sound Pocket Pink", "audio"],
  ["Carter's საბაშვო კომბინიზონი ფაჩუჩით", "kids"],
  ["Lorelli Magic Sleep საწოლ-მანეჟი", "kids"],
  ["Crucial BX500 500GB SATA 3", "computers"],
  ["Xiaomi Mesh System AC1200 2 pack White", "computers"],
  ["Epson EcoTank L6290", "computers"],
  ["Canon PIXMA G1430", "computers"],
  ["WD Purple Surveillance 6TB", "computers"],
  ["Seagate External HDD Light Blue 1TB", "computers"],
  ["Intel i7-12700K Tray 5.0 GHz", "computers"],
  ["Kingston FURY Renegade 4TB M.2 PCIe Gen 4", "computers"],
  ["BLINKMAX ჭიქების ნაკრები", "kitchen-dishes"],
  ["SONY ILCE-6400/B CEC", "photo-video"],
  ["Fujifilm Instax Mini 41 Black", "photo-video"],
  ["SBOX 15.6 ნოუთბუქის ჩანთა", "computer-accessories"],
  ["BroadLink Motion Sensor", "home-garden"],
  ["Topicrem AC Matifying Care სახის გელ-კრემი", "beauty"],
  ["Differin Soothing Moisturizer დამამშვიდებელი დამატენიანებელი", "beauty"],
  ["YVES SAINT LAURENT LIBRE INTENSE სუნამო", "beauty"],
  ["Gembird CAT6 UTP Patch Cord Red 1M", "cables-adapters"],
  ["Apple Magic Trackpad White", "computer-accessories"],
  ["METAL ACCENTS ზეთის დისპენსერი", "kitchen-dishes"],
  ["MESAUDA ტუჩსაცხი", "beauty"],
  ["DUO დეკორატიული ღობე", "home-garden"],
  ["INGCO CSLI1402 ტორსული ხერხი", "home-garden"],
  ["HOTECHE გადასაბმელი სადენები", "auto-accessories"],
  ["LIFEFIT სავარჯიშო რეზინი", "sport"],
  ["ARDESTO Creamer Prato Milk Jug რძის დოქი", "kitchen-dishes"],
  ["Odeska CAT5 UTP Indoor", "cables-adapters"],
  ["TP-Link USB3.0 to RJ-45 Adapter", "cables-adapters"],
  ["Logitech MK235 Combo Grey Wireless", "computer-accessories"],
  ["Logitech M185 Wireless Grey", "computer-accessories"],
  ["allfresh little joy მანქანის არომატიზატორი", "auto-accessories"],
  ["Uniq Hybrid Magclick Charging Lyden Galaxy S26 Dallas Black", "phone-accessories"],
  ["Moulin Roty რბილი ბურთი", "kids"],
  ["Oak Dining Table", "furniture"],
  ["Xiaomi Kingsmith Pneumatic Height Adjustable Table ETD2 Oak", "furniture"],
] as const;

for (const [title, expected] of cases) {
  const decision = categorizeProduct({ title });
  assert.equal(decision.publicCategorySlug, expected, `${title} should be ${expected}, received ${decision.publicCategorySlug}`);
  console.log(`${title} -> ${decision.publicCategorySlug}`);
}

console.log(`Verified ${cases.length} category mapping cases.`);
